# Mamba-KWS Medium Model Configuration

# Model configuration
model-size: "medium"
d-model: 128
n-layers: 10
d-state: 16

# Training configuration
batch-size: 64
epochs: 100
lr: 0.0005
weight-decay: 0.00018
warmup-frac: 0.12

# Data configuration
num-workers: 4

# Output configuration
experiment-name: "mamba_medium"